import React,{useEffect,useState,useRef} from 'react';
import {ProgressEvidence,AuthorSummary,HandoffEvidence} from './GenerationEvidence';
import {api,navigate} from './router';
const statuses:Record<string,string>={gathering_evidence:'正在整理诊断证据',probing_evidence:'正在补充验证',needs_manual_review:'交接冲突待人工复核',reviewing_spec:'独立可验证性审查',unsupported:'暂不支持',no_progress:'历史无进展停止，可恢复剩余预算',clarifying_contract:'契约 Agent 局部澄清',checking_contract:'独立校核契约修改',awaiting_requirement:'等待需求澄清',draft:'草稿',analyzing:'需求分析',awaiting_contract:'等待契约确认',building:'项目构建',evaluating:'独立评测生成',validating:'Docker 执行验证',teaching:'教学材料生成',awaiting_review:'等待作者审核',published:'已发布',failed:'失败',interrupted:'已中断',cancelled:'已取消',diagnosing:'执行失败分析中',repairing_build:'构建 Agent 修复中',waiting_backoff:'供应商暂时失败，等待重试',waiting_environment:'等待执行环境恢复',waiting_provider:'等待模型配置或服务恢复',awaiting_contract_review:'等待契约或评测歧义确认',budget_exhausted:'本批预算耗尽'};
const statusLabel=(j:any)=>j.status==='needs_manual_review'&&j.error?.category?.startsWith('evidence_')?'诊断证据待复核':statuses[j.status];
const gates:Record<string,string>={fingerprint_discriminates:'故障指纹不命中正常与参考',evasion_witnesses:'规避具有同场景行为反例',normal:'正常版本',reference:'参考修复',fault_trigger:'故障稳定触发',fault_regression:'故障版正常回归',evasion_rejected:'典型规避被识别',no_runtime_errors:'无加载、协议或执行错误'};
const assessments:Record<string,string>={generatable:'可生成',clarify:'需要澄清',simulation:'需要模拟',unsupported:'暂不支持'};
export function Generation({id}:{id?:string}){
 const [requirement,setRequirement]=useState(()=>localStorage.getItem('generation:requirement')||'');
 const [minutes,setMinutes]=useState(()=>localStorage.getItem('generation:minutes')||'45'),[difficulty,setDifficulty]=useState(()=>localStorage.getItem('generation:difficulty')||''),[preference,setPreference]=useState(()=>localStorage.getItem('generation:preference')||'');
 const [jobs,setJobs]=useState<any[]>([]),[job,setJob]=useState<any>(null),[contract,setContract]=useState<any>(null),[review,setReview]=useState<any>(null),[note,setNote]=useState(''),[approved,setApproved]=useState(false),[evaluationReason,setEvaluationReason]=useState(''),[simulation,setSimulation]=useState(false),[clarification,setClarification]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [regenerateOpen,setRegenerateOpen]=useState(false),[newBatch,setNewBatch]=useState(false),[repairNote,setRepairNote]=useState(''),[requestBudget,setRequestBudget]=useState(24),[budgetApproved,setBudgetApproved]=useState(false),[requestKey,setRequestKey]=useState(()=>crypto.randomUUID());
 const [requirementAnswers,setRequirementAnswers]=useState<Record<string,string>>({});
 const serverReviewDigest=useRef<string|null>(null);
 const serverContractVersion=useRef<number|null>(null);
 const direct=job?.project_flow==='direct-build-v1';
 const active=job&&['gathering_evidence','probing_evidence','reviewing_spec','analyzing','building','evaluating','validating','teaching','diagnosing','repairing_build','waiting_backoff','clarifying_contract','checking_contract'].includes(job.status);
 const call=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError(String(e))}finally{setBusy(false)}};
 async function reload(){if(id){const data=await api('/generation/jobs/'+id);setJob(data);if(serverReviewDigest.current!==(data.review_digest||null)){serverReviewDigest.current=data.review_digest||null;setReview(null);setApproved(false)}if(serverContractVersion.current!==data.contract_version){serverContractVersion.current=data.contract_version;setContract(data.contract);setReview(null);setApproved(false)}else setContract((old:any)=>old||(!['analyzing'].includes(data.status)?data.contract:null))}else setJobs(await api('/generation/jobs'))}
 useEffect(()=>{void call(reload);const timer=setInterval(()=>void reload().catch(e=>setError(String(e))),2000);return()=>clearInterval(timer)},[id]);
 useEffect(()=>{localStorage.setItem('generation:requirement',requirement);localStorage.setItem('generation:minutes',minutes);localStorage.setItem('generation:difficulty',difficulty);localStorage.setItem('generation:preference',preference)},[requirement,minutes,difficulty,preference]);
 useEffect(()=>{try{setRequirementAnswers(JSON.parse(localStorage.getItem('generation:answers:'+id+':'+job?.requirement_question?.id)||'{}'))}catch{setRequirementAnswers({})}},[id,job?.requirement_question?.id]);
 const action=(name:string,body?:unknown)=>void call(async()=>{await api('/generation/jobs/'+id+'/'+name,'POST',body);await reload()});
 return <main className="generation landing"><h1>故障题目生成</h1><p>描述训练需求 → 构建项目及内部规范 → 独立可验证性审查与 Docker 验证 → 自动修复 → 作者审核发布。模型提出的测试不是自动获得认可的标准。</p>
 {error&&<p className="banner error" role="alert">{error}</p>}
 {!id?<><section className="panel form"><p>新批次默认上限：24次模型请求、96000输出Token额度、600000输入字节、20分钟活动执行、10轮验证；提交后直接构建，无需确认技术契约；自动修复直到通过或预算耗尽，遇到环境、配置、需求阻塞或重复交接冲突时暂停。仅支持 Python 标准库、本地数据与模拟工具，不访问真实外部业务系统。MOCK模式不调用供应商。</p><label>训练需求（必填）<textarea aria-label="训练需求" value={requirement} onChange={e=>setRequirement(e.target.value)} rows={5} placeholder="例如：本地模拟工具响应丢失，调查为什么同一逻辑操作产生重复副作用…"/></label><label>预计时间（分钟，可选）<input aria-label="预计时间" type="number" min={10} max={120} value={minutes} onChange={e=>setMinutes(e.target.value)}/></label><label>难度偏好<input value={difficulty} onChange={e=>setDifficulty(e.target.value)}/></label><label>场景偏好<input value={preference} onChange={e=>setPreference(e.target.value)}/></label><button className="primary" disabled={busy||requirement.trim().length<8} onClick={()=>void call(async()=>{const created=await api('/generation/jobs','POST',{requirement,minutes:minutes?Number(minutes):null,difficulty,preference});navigate('/generate/'+created.id);await api('/generation/jobs/'+created.id+'/analyze','POST')})}>开始生成项目（调用模型）</button></section><h2>生成记录</h2>{jobs.map(j=><button key={j.id} className="history" onClick={()=>navigate('/generate/'+j.id)}><strong>{j.contract?.title||j.request.requirement.slice(0,60)}</strong><span>{statusLabel(j)} · {j.mode==='mock'?'MOCK 固定离线样例':'真实模型'}</span></button>)}</>:job&&<><p>记录 {job.id.slice(0,12)} · <strong role="status">{statusLabel(job)}</strong> · {job.mode==='mock'?'MOCK 固定样例，不是需求驱动真实生成':'真实模型生成'} · 模型请求 {job.request_count}/{job.budget?.policy.requests||10}</p><p>{job.request.requirement}</p><ol className="stages">{(direct?['building','reviewing_spec','evaluating','validating','teaching','awaiting_review','published']:['analyzing','awaiting_contract','building','evaluating','validating','teaching','awaiting_review','published']).map(s=><li key={s} aria-current={job.status===s?'step':undefined}>{statuses[s]}</li>)}</ol>
 {job.error&&<p role="alert" className="banner error">{job.error.category}：{job.error.reason}</p>}
 {direct&&job.contract&&<section className="panel form" aria-label="项目规范"><h2>项目规范 · 版本 {job.contract_version}</h2><p>由构建 Agent 随项目生成，独立审查后自动冻结，不需要你确认技术契约。发布前仍须人工审核。</p><h3>{job.contract.title}</h3><p>{job.contract.scenario}</p><p>{job.contract.symptom}</p><details><summary>公开行为、接口和模拟范围</summary><ul>{Object.entries(job.contract.behaviors).map(([key,value])=><li key={key}>{key}：{String(value)}</li>)}</ul><p>{job.contract.input_domain}</p><p>{job.contract.simulation}</p><pre>{JSON.stringify({input:job.contract.input_schema,output:job.contract.output_schema,files:job.contract.files},null,2)}</pre></details></section>}
 {direct&&job.spec_reviews?.length>0&&<section className="panel form"><h3>独立可验证性审查记录</h3>{job.spec_reviews.map((r:any)=><details key={r.asset}><summary>规范 v{r.contract_version} · {({approve:'审查通过',revise:'退回构建补齐',need_user:'需求需要澄清',unsupported:'暂不支持'} as Record<string,string>)[r.decision]}</summary><p>{r.reason}</p>{r.issues.map((i:any)=><p key={i.path}>{i.path}：{i.reason}</p>)}</details>)}</section>}
 {job.status==='awaiting_requirement'&&job.requirement_question&&<section className="panel form"><h2>需要你明确需求</h2><p>{job.requirement_question.reason}</p><p>只有需求存在多种解释时才会提问；平台设计缺项会自动退回构建；回答后在本批剩余预算内继续。</p>{job.requirement_question.questions.map((q:any)=><fieldset key={q.id}><legend>{q.text}</legend><p>{q.impact}</p>{q.options.map((option:string)=><button type="button" key={option} disabled={busy} onClick={()=>{const next={...requirementAnswers,[q.id]:option};setRequirementAnswers(next);localStorage.setItem('generation:answers:'+id+':'+job.requirement_question.id,JSON.stringify(next))}}>{option}</button>)}<label>你的说明<textarea aria-label={'需求回答 '+q.id} maxLength={2000} value={requirementAnswers[q.id]||''} onChange={e=>{const next={...requirementAnswers,[q.id]:e.target.value};setRequirementAnswers(next);localStorage.setItem('generation:answers:'+id+':'+job.requirement_question.id,JSON.stringify(next))}}/></label></fieldset>)}<button className="primary" disabled={busy||job.requirement_question.questions.some((q:any)=>!requirementAnswers[q.id]?.trim())} onClick={()=>void call(async()=>{const question=job.requirement_question;await api('/generation/jobs/'+id+'/requirement-answer','POST',{expected_revision:job.revision,question_id:question.id,answers:requirementAnswers});localStorage.removeItem('generation:answers:'+id+':'+question.id);await reload()})}>提交需求澄清并继续（消耗Token）</button></section>}
 {job.contract_reviews?.length>0&&<section className="panel form"><h2>契约局部修订记录</h2><p>未改动字段保持原值；修订后的代码和检查会重新生成并验证。独立模型校核不替代发布前人工审核。</p>{job.contract_reviews.map((r:any)=><details key={r.id}><summary>契约 v{r.from_version}{r.to_version?' → v'+r.to_version:''} · {r.to_version?'局部修订已应用':r.proposal.decision==='need_user'?'需求澄清':r.proposal.decision==='clear'?'契约明确':'校核要求重做'}</summary><p>{r.proposal.reason}</p><p>校核：{r.review.reason}</p>{r.proposal.changes.map((c:any)=><div key={c.path}><strong>{c.path}</strong><pre>{JSON.stringify(c.before,null,2)}{' → '}{JSON.stringify(c.after,null,2)}</pre><p>依据 {c.source}：{c.quote}</p><p>{c.reason}</p></div>)}</details>)}</section>}
 {job.assessment&&<section className="panel form"><h2>{assessments[job.assessment]}</h2><p>{job.rationale}</p>{job.questions?.map((q:string)=><p key={q}>{q}</p>)}{['clarify','unsupported'].includes(job.assessment)&&<button onClick={()=>{localStorage.setItem('generation:requirement',job.request.requirement);navigate('/generate')}}>修改需求并新建分析记录</button>}</section>}
 {contract&&!direct&&<section className="panel form"><h2>公开契约 · 版本 {job.contract_version}</h2><p>确认后冻结；修改会创建新契约版本，使所有下游资产重新生成和验证。</p>{(['title','scenario','symptom','input_domain','simulation'] as const).map(key=><label key={key}>{({title:'标题',scenario:'场景',symptom:'公开症状',input_domain:'输入范围',simulation:'模拟范围'})[key]}<textarea aria-label={'契约 '+key} disabled={active||['published','cancelled'].includes(job.status)} value={contract[key]} onChange={e=>setContract({...contract,[key]:e.target.value})}/></label>)}<label>行为契约（每行 ID: 说明）<textarea aria-label="契约行为" disabled={active||['published','cancelled'].includes(job.status)} value={Object.entries(contract.behaviors).map(([k,v])=>k+': '+v).join('\n')} onChange={e=>setContract({...contract,behaviors:Object.fromEntries(e.target.value.split('\n').map(line=>{const split=line.indexOf(':');return [line.slice(0,split),line.slice(split+1).trim()]}))})}/></label>{['constraints','exclusions'].map(key=><label key={key}>{key==='constraints'?'约束':'不考察范围'}<textarea disabled={active||['published','cancelled'].includes(job.status)} value={contract[key].join('\n')} onChange={e=>setContract({...contract,[key]:e.target.value.split('\n')})}/></label>)}<details><summary>公开接口、文件与运行范围</summary><pre>{JSON.stringify({input:contract.input_schema,output:contract.output_schema,files:contract.files},null,2)}</pre><p>固定 Python 标准库环境，无网络；不可自定义镜像或安装依赖。</p></details>
 <button disabled={busy||active||['published','cancelled'].includes(job.status)} onClick={()=>void call(async()=>{const next=await api('/generation/jobs/'+id+'/contract','PUT',contract);setJob(next);setContract(next.contract);setReview(null);setApproved(false)})}>保存为新契约版本</button>
 {job.status==='awaiting_contract'&&['generatable','simulation'].includes(job.assessment)&&<><label><input type="checkbox" checked={simulation} onChange={e=>setSimulation(e.target.checked)}/>我确认上述模拟范围；不将其当作真实外部系统验证</label><button className="primary" disabled={busy||(!!contract.simulation&&!simulation)||JSON.stringify(contract)!==JSON.stringify(job.contract)} onClick={()=>action('confirm',{version:job.contract_version,simulation_confirmed:simulation})}>确认契约并生成项目（调用模型）</button></>}
 </section>}
 {!direct&&!active&&!['published','cancelled','draft','awaiting_requirement'].includes(job.status)&&<section className="panel form"><h3>澄清或修改契约</h3><textarea aria-label="契约澄清要求" value={clarification} onChange={e=>setClarification(e.target.value)} placeholder="说明接口、行为或支持范围中的歧义；生成新版本后必须重新确认。"/><button disabled={busy||clarification.trim().length<10} onClick={()=>void call(async()=>{await api('/generation/jobs/'+id+'/reanalyze','POST',{reason:clarification});setContract(null);setReview(null);setApproved(false);await reload()})}>重新设计契约（新版本，调用模型）</button></section>}
 {job.status==='draft'&&<button disabled={busy} onClick={()=>action('analyze')}>开始生成项目（调用模型）</button>}
 {job.budget&&<section className="panel form"><h2>本批预算与自动修复</h2><p>{job.role_policy==='consolidated-v1'?'三个角色：项目构建（设计、构建、修复）；评测（规范审查、独立测试、故障复现、失败分析）；教学。各阶段上下文隔离':direct?'构建 Agent 同时负责规范设计与实现；独立评测负责可验证性审查和测试':'历史流程：契约、构建、评测、失败诊断、教学'}；自动修复 {job.repair_round||0} 轮。</p><p>模型请求 {job.budget.requests}/{job.budget.policy.requests} · 输出记账额度 {job.budget.output_charged}/{job.budget.policy.output_tokens} Token · 输入 {job.budget.input_bytes}/{job.budget.policy.input_bytes} 字节 · 验证 {job.budget.validations}/{job.budget.policy.validations} 轮</p><p>活动执行累计 {Math.round(job.budget.active_seconds+(job.budget.active_started?Math.max(0,Date.now()/1000-job.budget.active_started):0))} 秒 / {job.budget.policy.seconds} 秒；{job.budget.unknown_usage} 次用量未知，按预留上限记账。额度不是精确费用。</p>{job.progress_reason&&<p>当前修复分类：{job.progress_reason.category}；依据契约行为：{job.progress_reason.behaviors.join('、')}。私有诊断仅在作者审核区可见。</p>}{job.parent_job&&<a href={'/generate/'+job.parent_job}>查看原尝试（原记录保持不变）</a>}<details><summary>本批失败与恢复记录（{job.failures?.length||0}）</summary>{job.failures?.map((f:any)=><p key={f.id}>{f.stage} · 证据 {f.id.slice(0,12)} · 矩阵 {f.matrix_id?.slice(0,12)||'尚未执行'}</p>)}</details></section>}
 {['needs_manual_review','no_progress','failed','interrupted','budget_exhausted','waiting_environment','waiting_provider','awaiting_contract_review'].includes(job.status)&&<section className="panel form"><button disabled={busy} onClick={()=>{setRegenerateOpen(true);setNewBatch(!job.policy_version||job.status==='budget_exhausted'||job.status==='failed');setBudgetApproved(false)}}>重新生成（消耗Token）</button>{regenerateOpen&&<><p>检查点：{job.checkpoint||job.stage}。已有资产沿用，目标修复与受影响验证重新执行。可恢复状态且仍有预算时恢复检查点；历史无进展停止可恢复剩余预算。新预算批次保留旧记录，不重置旧计数。环境、密钥或契约阻塞必须先解决。</p><label>修复依据<textarea aria-label="修复依据" value={repairNote} onChange={e=>setRepairNote(e.target.value)} placeholder="描述契约内问题和执行证据；不以参考实现失败为理由改期望。"/></label><label><input type="checkbox" checked={newBatch} disabled={!job.policy_version||['budget_exhausted','failed'].includes(job.status)} onChange={e=>{setNewBatch(e.target.checked);setBudgetApproved(false)}}/>创建关联旧记录的新预算批次</label>{newBatch&&<><label>新批次最大模型请求<input aria-label="新批次最大模型请求" type="number" min={1} max={24} value={requestBudget} onChange={e=>setRequestBudget(Number(e.target.value))}/></label><p>其余上限：96000输出Token、600000输入字节、20分钟活动执行、10轮验证；均为硬上限，不保证生成成功。</p><label><input type="checkbox" checked={budgetApproved} onChange={e=>setBudgetApproved(e.target.checked)}/>我明确批准上述新批次预算；旧记录保持不变</label></>}<button disabled={busy||(newBatch&&!budgetApproved)} onClick={()=>void call(async()=>{const next=await api('/generation/jobs/'+id+'/regenerate','POST',{expected_revision:job.revision||0,idempotency_key:requestKey,repair_note:repairNote,new_batch:newBatch,...(newBatch?{budget:{requests:requestBudget,output_tokens:96000,input_bytes:600000,seconds:1200,validations:10}}:{})});setRequestKey(crypto.randomUUID());setRegenerateOpen(false);if(next.id!==id)navigate('/generate/'+next.id);else await reload()})}>{newBatch?'确认新预算并重新生成':'恢复当前批次'}</button></>}</section>}
 {job.budget&&<ProgressEvidence job={job}/>}
 {active&&<button disabled={busy} onClick={()=>action('cancel')}>取消后续阶段</button>}
 {job.matrix&&<section className="panel form"><h2 id={'matrix-'+job.matrix.id}>验证矩阵 · {job.matrix.passed?'自动检查通过，仍须审核':'尚未通过'}</h2><p>{job.matrix.trust}</p><p>执行 {job.matrix.id} · {job.matrix.checks.length} 项</p>{Object.entries(job.matrix.gates||{}).map(([k,v])=><p key={k}>{gates[k]||k}：{v?'通过':'未通过'}</p>)}<details><summary>逐项执行状态</summary>{job.matrix.checks.map((c:any)=><p key={c.id} id={'check-'+c.id} title={c.id}>{c.id.slice(0,12)} · {c.version} / {c.case} · {c.status} · {c.duration} 秒{c.error?' · '+c.error:''}</p>)}</details></section>}
 {['needs_manual_review','no_progress','awaiting_review','published','failed','budget_exhausted','awaiting_contract_review','waiting_environment','waiting_provider','interrupted','awaiting_requirement'].includes(job.status)&&<section className="panel form"><h2>作者审核（包含答案，与训练视图分离）</h2><button disabled={busy} onClick={()=>void call(async()=>setReview(await api('/author/generation/'+id)))}>打开私有资产审核</button>{review&&<><p>{review.trust}</p>{job.status==='needs_manual_review'&&<p role="status">自动纠错已停止。请核对冲突双方和已有证据；恢复前需要提供新的依据，不会自动重发模型请求。</p>}<HandoffEvidence review={review}/><AuthorSummary review={review}/><details><summary>契约、全部实现、独立检查与教学材料</summary><pre className="review-assets">{JSON.stringify({assets:review.assets,matrix:review.matrix,diagnoses:review.diagnoses,failure_history:review.failure_history,asset_revisions:review.asset_revisions,handoff_conflicts:review.handoff_conflicts,handoff_rejections:review.handoff_rejections,candidate_history:review.candidate_history,evidence_request:review.evidence_request},null,2)}</pre></details><p>请逐项检查：契约无歧义、期望值正确、隐藏检查不追加需求、故障符合症状、题面无答案泄漏、三级提示恰当。自动通过不替代这次审核。</p>{job.status==='failed'&&job.stage==='validation'&&<><label>评测自身问题（必须引用公开契约，不能因为参考实现失败就改期望）<textarea aria-label="评测问题依据" value={evaluationReason} onChange={e=>setEvaluationReason(e.target.value)}/></label><button disabled={busy||evaluationReason.trim().length<10} onClick={()=>void call(async()=>{await api('/author/generation/'+id+'/repair-evaluation','POST',{reason:evaluationReason});setReview(null);setApproved(false);await reload()})}>修复评测（调用模型，审核指导，重新验证）</button></>}
 <textarea aria-label="审核依据" placeholder="记录具体检查过的行为和资产，不要只写同意。" value={note} onChange={e=>setNote(e.target.value)}/><label><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>我已审核当前资产及验证证据，确认可以发布</label><button className="primary" disabled={busy||!approved||note.trim().length<10||job.status!=='awaiting_review'} onClick={()=>void call(async()=>{await api('/author/generation/'+id+'/publish','POST',{approved,note,review_digest:review.review_digest});await reload()})}>审核通过并发布</button></>}</section>}
 {job.status==='published'&&<section><h2>已冻结发布 · v{job.published_version}</h2><button disabled={busy} onClick={()=>void call(async()=>{const next=await api('/author/generation/'+id+'/new-version','POST');navigate('/generate/'+next.id)})}>基于此任务创建新版本</button><button onClick={()=>navigate('/library/'+job.published_task)}>前往题库</button><button onClick={()=>void call(async()=>{const session=await api('/sessions','POST',{task_id:job.published_task});navigate('/training/'+session.id)})}>开始训练</button></section>}
 <details><summary>阶段调用审计</summary>{job.attempts?.map((a:any,i:number)=><p key={i}>{a.stage} #{a.attempt} · {a.status} · {a.stage==='evaluation'?(a.blind?'独立盲测上下文':'审核指导，非完全盲测'):''} · 输入摘要 {a.input_hash?.slice(0,12)} · 模型 {a.metadata?.model||'未知'}</p>)}</details><button onClick={()=>navigate('/generate')}>返回生成记录</button>
 </>}
 </main>;
}
