import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import Editor, {loader} from '@monaco-editor/react';
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';
import 'monaco-editor/esm/vs/basic-languages/python/python.contribution';
import editorWorker from 'monaco-editor/esm/vs/editor/editor.worker?worker';
import './style.css';
import {Markdown} from './Markdown';
(self as unknown as {MonacoEnvironment: unknown}).MonacoEnvironment={getWorker:()=>new editorWorker()};
loader.config({monaco});

type Task={id:string;title:string;version:string;brief:string;tags:string[];minutes:number;environment:string};
type Check={id:string;status:string;detail:string;group:string;visibility:string};
type Hint={id:string;level:number;time:number;text:string};
type Run={id:string;snapshot:string;kind:string;status:string;duration:number|null;exit_code:number|null;output:string;checks:Check[];hints:Hint[]};
type Report={id:string;run_id:string;snapshot:string;objective:Run;feedback:string;feedback_status?:string;feedback_error?:{category:string;reason:string};diagnosis:string};
type Event={id:string;role:string;content:string;name?:string;status?:string;summary?:string};
type Session={id:string;task_id:string;version:string;status:string;hint_level:number;code:string;diagnosis:string;events:Event[];runs:Run[];reports:Report[];hints:Hint[]};
type Health={agent_mode:string;docker_available:boolean;reason:string};
async function api<T>(url:string,method='GET',body?:unknown):Promise<T>{
 const res=await fetch('/api'+url,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
 const data=await res.json(); if(!res.ok)throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;
}
const stateName:Record<string,string>={queued:'排队中',running:'执行中',passed:'通过',failed:'失败',error:'错误',timeout:'超时',interrupted:'已中断',active:'训练中',submitted:'已提交'};
function App(){
 const [tasks,setTasks]=useState<Task[]>([]),[history,setHistory]=useState<Session[]>([]),[health,setHealth]=useState<Health|null>(null);
 const [session,setSession]=useState<Session|null>(null),[code,setCode]=useState(''),[diagnosis,setDiagnosis]=useState(''),[message,setMessage]=useState('');
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState('tests'),[publicTests,setPublicTests]=useState('');
 const dirty=!!session&&(code!==session.code||diagnosis!==session.diagnosis);
 const task=tasks.find(t=>t.id===session?.task_id);
 async function guard(name:string,fn:()=>Promise<void>){setBusy(name);setError('');try{await fn()}catch(e){setError(String(e))}finally{setBusy('')}}
 async function reload(id:string){const next=await api<Session>('/sessions/'+id);setSession(next);return next}
 async function open(id:string){await guard('加载训练',async()=>{const next=await reload(id);let draft:null|{code:string;diagnosis:string}=null;try{draft=JSON.parse(localStorage.getItem('draft:'+id)||'null')}catch{}setCode(draft?.code??next.code);setDiagnosis(draft?.diagnosis??next.diagnosis);localStorage.setItem('session',id);setTab('tests');setPublicTests('')})}
 useEffect(()=>{void guard('初始化',async()=>{const [t,h,x]=await Promise.all([api<Task[]>('/tasks'),api<Session[]>('/sessions'),api<Health>('/health')]);setTasks(t);setHistory(h);setHealth(x);const id=localStorage.getItem('session');if(id)await open(id)})},[]);
 useEffect(()=>{if(session){if(dirty)localStorage.setItem('draft:'+session.id,JSON.stringify({code,diagnosis}));else localStorage.removeItem('draft:'+session.id)}},[code,diagnosis,session?.id,dirty]);
 useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn)},[dirty]);
 useEffect(()=>{if(!session)return;const id=session.id;const timer=setInterval(()=>{api<Session>('/sessions/'+id).then(next=>setSession(current=>current?.id===id?next:current)).catch(e=>setError('刷新执行状态失败：'+e))},2000);return()=>clearInterval(timer)},[session?.id]);
 async function save(){if(!session)return;await api('/sessions/'+session.id+'/files','PUT',{code,diagnosis});await reload(session.id);setNotice('代码与诊断已保存')}
 async function execute(submit:boolean){if(!session)return;await guard(submit?'提交评测':'运行测试',async()=>{await save();await api('/sessions/'+session.id+(submit?'/submit':'/runs'),'POST');await reload(session.id);setTab(submit?'reports':'tests');setNotice('执行已创建，结果绑定到此次保存的代码快照')})}
 const evidenceIds=session?[...session.events.map(e=>e.id),...session.runs.map(r=>r.id),...session.hints.map(h=>h.id)]:[];
 const active=session?.runs.some(r=>['queued','running'].includes(r.status));
 return <><header><button className="brand" onClick={()=>{setSession(null);localStorage.removeItem('session');void api<Session[]>('/sessions').then(setHistory)}}>◈ AgentLab <span>INTERVIEW / V0.1</span></button><span>本地工程实操 · 证据驱动反馈</span><b className={health?.agent_mode==='mock'?'badge mock':'badge'}>{health?.agent_mode==='mock'?'MOCK · 确定性辅导':'真实模型模式'}</b></header>
 {error&&<div role="alert" className="banner error">{error}<button onClick={()=>setError('')}>关闭</button></div>}
 {health&&!health.docker_available&&<div className="banner warning">执行环境未就绪：{health.reason} 编辑、保存和提示仍可使用。<button onClick={()=>void guard('检查 Docker',async()=>setHealth(await api<Health>('/health')))}>重新检查</button></div>}
 {busy&&<div className="progress" role="status">{busy}…</div>}
 {!session?<main className="landing"><div className="eyebrow">BUILD. DEBUG. EXPLAIN.</div><h1>把 Agent 故障，变成工程经验。</h1><p className="lead">进入独立代码工作区，通过测试定位问题。提交修复和诊断，用真实执行证据复盘。</p><div className="cards">{tasks.map((t,i)=><article key={t.id}><div className="tasknum">实验 0{i+1}<span>v{t.version}</span></div><h2>{t.title}</h2><div className="tags">{t.tags.map(tag=><span key={tag}>{tag}</span>)}</div><p>{t.brief}</p><footer><span>约 {t.minutes} 分钟</span><button disabled={!!busy} onClick={()=>void guard('创建会话',async()=>{const obj=await api<Session>('/sessions','POST',{task_id:t.id});await open(obj.id)})}>开始训练 ↗</button></footer></article>)}</div><h2>训练历史</h2>{!history.length?<p className="muted">暂无训练，选择一个故障任务开始。</p>:history.map(h=><button className="history" key={h.id} onClick={()=>void open(h.id)}><strong>{tasks.find(t=>t.id===h.task_id)?.title}</strong><code>{h.id.slice(0,12)}</code><span>{stateName[h.status]||h.status} → 恢复训练与报告</span></button>)}<p className="muted">训练反馈不预测真实招聘结果。所有工作区代码仅在 Docker 内执行。</p></main>:<main className="workspace"><div className="worktitle"><div><div className="eyebrow">{session.task_id.toUpperCase()} / v{session.version} / {session.id.slice(0,12)}</div><h1>{task?.title}</h1></div><div className="actions"><span className={dirty?'unsaved':'muted'}>{dirty?'● 有未保存修改（草稿已本地保留）':'✓ 已保存'}</span><button disabled={!!busy} onClick={()=>void guard('保存',save)}>保存</button><button disabled={!!busy||active||!health?.docker_available} onClick={()=>void execute(false)}>保存并运行公开测试</button><button className="primary" disabled={!!busy||active||!health?.docker_available} onClick={()=>void execute(true)}>保存并提交评测</button></div></div>{notice&&<p className="notice" role="status">{notice}</p>}
 <div className="columns"><aside className="panel brief"><h3>任务说明</h3><p>{task?.brief}</p><h3>环境与约束</h3><p>{task?.environment}</p><p>每个会话使用独立副本。仅允许编辑 solution.py；公开测试只读。</p><h3>文件</h3><button className="file">▧ solution.py {dirty?'●':''}</button><button className="file" onClick={()=>void guard('读取公开测试',async()=>{const value=await api<{test:string;cases:unknown}>('/sessions/'+session.id+'/public-tests');setPublicTests(value.test+'\n'+JSON.stringify(value.cases,null,2));setTab('public')})}>▤ public_test.py / 固定数据</button><h3>诊断说明</h3><textarea aria-label="诊断说明" value={diagnosis} onChange={e=>setDiagnosis(e.target.value)} placeholder="观察到了什么？如何定位？修复取舍与回归验证？" rows={9}/></aside>
 <section className="editorarea"><div className="panel editor"><div className="panelhead">solution.py <span>Python · UTF-8</span></div><Editor height="420px" language="python" theme="vs-dark" value={code} onChange={v=>setCode(v??'')} options={{fontSize:14,minimap:{enabled:false},scrollBeyondLastLine:false,automaticLayout:true,padding:{top:16}}} loading={<p>正在加载本地编辑器…</p>}/></div><div className="panel evidence"><nav>{[['tests','测试证据'],['reports','提交报告'],['public','公开测试']].map(([key,label])=><button key={key} className={tab===key?'selected':''} onClick={()=>setTab(key)}>{label}{key==='reports'?` (${session.reports.length})`:''}</button>)}</nav>{tab==='public'?<pre>{publicTests||'点击左侧公开测试文件查看。'}</pre>:tab==='tests'?session.runs.length?session.runs.map(r=><RunView key={r.id} run={r}/>):<p className="empty">尚未运行测试。保存并运行后，这里会显示真实证据。</p>:<>{active&&<p role="status">评测正在进行，刷新页面后仍可继续查询。</p>}{!session.reports.length&&<p className="empty">尚无报告。提交后将创建新的代码快照并重新评测。</p>}{session.reports.map(r=><article className="report" key={r.id} id={r.id}><h3>训练报告 <code>{r.id.slice(0,12)}</code></h3><p>代码快照 <button onClick={()=>void guard('查看提交代码',async()=>{const snap=await api<{code:string}>('/sessions/'+session.id+'/snapshots/'+r.snapshot);setPublicTests('提交快照 '+r.snapshot+'\n'+snap.code);setTab('public')})}>{r.snapshot.slice(0,16)} ↗</button></p><RunView run={r.objective}/><h4>诊断说明</h4><p>{r.diagnosis||'未提供；无法评价定位过程和技术取舍。'}</p><h4>提示使用 · {r.objective.hints.length} 次</h4>{r.objective.hints.map(h=><p id={h.id} key={h.id}>L{h.level} · {new Date(h.time*1000).toLocaleString()} · <code>{h.id}</code></p>)}<h4>模型反馈 · {r.feedback_status==='generating'?'生成中':r.feedback_status==='generated'?'已生成':r.feedback_status==='failed'?'生成失败':'未生成'}</h4>{r.feedback_status==='generating'?<p role="status">正在请求模型反馈；客观结果已保存。</p>:r.feedback_status==='failed'?<p role="alert">{r.feedback_error?.reason||'模型反馈生成失败'}（{r.feedback_error?.category||'unknown'}）。客观结果不受影响。</p>:<Markdown text={r.feedback} ids={evidenceIds}/>}<a href={'#'+r.run_id}>定位执行证据 {r.run_id.slice(0,12)}</a></article>)}</>}</div></section>
 <aside className="panel chat"><div className="panelhead">训练 Agent <span>{health?.agent_mode==='mock'?'MOCK':'MODEL'}</span></div><p className="muted">{health?.agent_mode==='mock'?'确定性 mock，不是真实智能辅导。':'单 Agent · 每轮最多 6 次工具调用。'} Agent 只读取已保存代码，不代写修复。</p><div className="messages">{!session.events.length&&<p className="empty">描述你的观察，或先运行一次公开测试。</p>}{session.events.map(e=>e.role==='tool'?<details key={e.id} id={e.id}><summary>工具 · {e.name} · {e.status==='ok'?'完成':e.status==='error'?'失败':'状态未记录'} · 证据 {e.id.slice(0,8)}<span className="tool-summary">{e.summary||'展开查看工具结果'}</span></summary><p>完整证据 ID：<code>{e.id}</code></p><pre>{e.content}</pre></details>:<div key={e.id} id={e.id} className={'bubble '+e.role}><small>{e.role==='user'?'你':'训练 Agent'} · {e.id.slice(0,8)}</small>{e.role==='assistant'?<Markdown text={e.content} ids={evidenceIds}/>:<p>{e.content}</p>}</div>)}</div><div className="composer"><textarea aria-label="给 Agent 的消息" value={message} onChange={e=>setMessage(e.target.value)} placeholder="描述现象、提出推测或请 Agent 检查证据…"/><div className="actions"><button disabled={!!busy||session.hint_level>=3} onClick={()=>void guard('请求提示',async()=>{await api('/sessions/'+session.id+'/hint','POST');await reload(session.id)})}>{session.hint_level>=3?'已获取全部提示':`请求提示 · ${session.hint_level+1}/3`}</button><button className="primary" disabled={!!busy||!message.trim()} onClick={()=>void guard('Agent 思考中',async()=>{await api('/sessions/'+session.id+'/chat','POST',{message});setMessage('');await reload(session.id)})}>发送</button></div></div></aside></div></main>}</>;
}
function RunView({run:r}:{run:Run}){return <div className="run" id={r.id}><div className="runhead"><b className={'status '+r.status}>{stateName[r.status]||r.status}</b><span>{r.kind==='submission'?'提交评测':'公开测试'}</span><span>{r.duration===null?(['queued','running'].includes(r.status)?'计时中':'耗时未记录'):r.duration+' 秒'} · 退出码 {r.exit_code??'—'}</span></div><details><summary>执行 {r.id.slice(0,8)} · 快照 {r.snapshot.slice(0,8)}</summary><code>执行 {r.id}</code><br/><code>快照 {r.snapshot}</code></details><p>{r.output||'等待执行结果…'}</p>{r.checks.map(c=><details key={c.id} id={r.id+'-'+c.id}><summary><span className={'status '+c.status}>{stateName[c.status]||c.status}</span> {c.id} · {c.group==='regression'?'正常回归':c.group==='constraint'?'约束检查':'目标行为'} · {c.visibility==='hidden'?'隐藏检查':'公开检查'}</summary><pre>{c.detail}</pre></details>)}</div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
