import {test,expect} from '@playwright/test';

test('三个主导航深链接、返回与草稿隔离',async({page,request})=>{
 await page.goto('/generate');
 await expect(page.getByRole('link',{name:'故障题目生成',exact:true})).toHaveAttribute('aria-current','page');
 await page.getByLabel('训练需求').fill('研究上下文压缩后关键约束丢失的工程机制');
 await page.getByRole('link',{name:'个人工程项目训练',exact:true}).click();
 await expect(page.getByRole('heading',{name:'尚未开放'})).toBeVisible();
 await expect(page.getByRole('button',{name:/上传|导入|开始训练/})).toHaveCount(0);
 await page.reload();await expect(page.getByRole('heading',{name:'尚未开放'})).toBeVisible();
 await page.goBack();await expect(page.getByLabel('训练需求')).toHaveValue('研究上下文压缩后关键约束丢失的工程机制');
 await page.goForward();await expect(page.getByRole('heading',{name:'尚未开放'})).toBeVisible();
 await page.getByRole('link',{name:'题库',exact:true}).click();
 await page.getByRole('button',{name:'开始训练 ↗'}).first().click();
 await expect(page).toHaveURL(/\/training\/[a-f0-9]{32}$/);
 const id=await page.evaluate(()=>localStorage.getItem('session'));
 await page.getByLabel('诊断说明').fill('导航切换保留本会话草稿');
 await page.getByRole('link',{name:'故障题目生成',exact:true}).click();
 await expect(page.getByLabel('训练需求')).toHaveValue('研究上下文压缩后关键约束丢失的工程机制');
 await page.goBack();await expect(page.getByLabel('诊断说明')).toHaveValue('导航切换保留本会话草稿');
 const other=await (await request.post('/api/sessions',{data:{task_id:'retry'}})).json();
 await page.goto('/training/'+other.id);await expect(page.getByLabel('诊断说明')).toHaveValue('');
 await page.goto('/training/'+id);await expect(page.getByLabel('诊断说明')).toHaveValue('导航切换保留本会话草稿');
 await page.setViewportSize({width:390,height:844});
 for(const name of ['故障题目生成','题库','个人工程项目训练'])await expect(page.getByRole('link',{name,exact:true})).toBeInViewport();
});

test('生成审核发布及 Docker 训练报告闭环（明确 MOCK）',async({page,request},info)=>{
 test.setTimeout(180000);
 const health=await (await request.get('/api/health')).json();test.skip(!health.docker_available,'Docker 不可用，禁止宿主降级');
 await page.goto('/generate');
 await page.getByLabel('训练需求').fill('离线平台流程验收：固定样例不作为真实需求生成证明');
 await page.getByRole('button',{name:'开始生成项目（调用模型）',exact:true}).click();
 await expect(page).toHaveURL(/\/generate\/[a-f0-9]{32}$/);
 const id=page.url().split('/').pop();
 await expect(page.getByText(/MOCK 固定样例，不是需求驱动真实生成/)).toBeVisible();
 await expect(page.getByRole('button',{name:'确认契约并生成项目（调用模型）'})).toHaveCount(0);
 await page.getByRole('link',{name:'题库',exact:true}).click();
 expect((await (await request.get('/api/tasks')).json()).some((t:any)=>t.id==='gen_'+id)).toBe(false);
 await page.goto('/generate/'+id);
 await expect(page.locator('.generation strong[role=status]')).toHaveText('等待作者审核',{timeout:100000});
 await page.getByRole('button',{name:'打开私有资产审核'}).click();
 await page.getByText('契约、全部实现、独立检查与教学材料',{exact:true}).click();
 await expect(page.locator('pre.review-assets').filter({hasText:'"faulty"'})).toContainText('faulty');
 await expect(page.getByRole('button',{name:'审核通过并发布'})).toBeDisabled();
 await page.getByLabel('审核依据').fill('自动化离线审核表单测试（不构成人工审核）：正数、负数、多元素、空集期望均正确，两种规避被拒绝，提示无完整代码。');
 await page.getByLabel('我已审核当前资产及验证证据，确认可以发布').check();
 await page.getByRole('button',{name:'审核通过并发布'}).click();
 await expect(page.getByRole('heading',{name:/已冻结发布/})).toBeVisible();
 const job=await (await request.get('/api/generation/jobs/'+id)).json();
 expect(job.role_policy).toBe('consolidated-v1');
 expect(job.attempts.filter((a:any)=>['spec_review','evaluation','fingerprint'].includes(a.stage)).every((a:any)=>a.role_id==='evaluator')).toBe(true);
 expect(job.attempts.find((a:any)=>a.stage==='project_build').role_id).toBe('builder');
 const review=await (await request.get('/api/author/generation/'+id)).json();
 expect(job.matrix.fault_checks).toBeUndefined();
 expect(review.assets.fingerprint.checks.length).toBeGreaterThan(0);
 expect(job.project_flow).toBe('direct-build-v1');
 expect(job.attempts.some((a:any)=>a.stage==='design'||a.stage==='contract_review')).toBe(false);
 expect(job.spec_reviews[0].decision).toBe('approve');
 expect(job.matrix.gates.fingerprint_discriminates).toBe(true);
 await page.getByRole('button',{name:'前往题库',exact:true}).click();
 await expect(page.getByRole('link',{name:'题库',exact:true})).toHaveAttribute('aria-current','page');
 await expect(page.locator('.cards')).toContainText('生成任务');
 await page.getByRole('button',{name:'开始训练 ↗'}).click();
 await expect(page).toHaveURL(/\/training\/[a-f0-9]{32}$/);
 await expect(page.getByText('任务说明',{exact:true})).toBeVisible();
 const session=new URL(page.url()).pathname.split('/').pop();
 await page.context().grantPermissions(['clipboard-read','clipboard-write']);
 for(const [file,code] of Object.entries(review.assets.build.reference)){
  await page.getByRole('button',{name:'打开文件 '+file,exact:true}).click();
  await page.evaluate(text=>navigator.clipboard.writeText(text),String(code));
  await page.locator('.monaco-editor textarea').first().focus();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.press('ControlOrMeta+V');
 }
 await page.getByLabel('诊断说明').fill('所有整数都应参与累加，核对空列表与多个元素。');
 await page.getByRole('button',{name:'保存并运行公开测试'}).click();
 await expect(page.locator('.run').first().locator('.runhead .status')).toHaveText('通过',{timeout:60000});
 await page.getByRole('button',{name:'保存并提交评测'}).click();
 await expect(page.locator('.report .runhead .status')).toHaveText('通过',{timeout:60000});
 await page.reload();await expect(page.getByRole('button',{name:'保存',exact:true})).toBeEnabled();await page.getByRole('button',{name:/提交报告/}).click();
 await expect(page.locator('.report .runhead .status')).toHaveText('通过');
 const state=await (await request.get('/api/sessions/'+session)).json();
 expect(state.task_id).toBe(job.published_task);expect(state.reports[0].snapshot).toBe(state.reports[0].objective.snapshot);
 await info.attach('generated-flow',{body:JSON.stringify({job,session,report:state.reports[0]},null,2),contentType:'application/json'});
});

test('失败生成不可发布',async({page,request})=>{
 const created=await (await request.post('/api/generation/jobs',{data:{requirement:'测试失败状态不得发布到题库'}})).json();
 await page.route('**/api/generation/jobs/'+created.id,async route=>{const res=await route.fetch();const body=await res.json();body.status='failed';body.attempts=[{role:'独立评测 Agent',status:'failed',failure_kind:'patch_rejected',attempt:1},{role:'契约 Agent',status:'failed',failure_kind:'response_format',attempt:2},{role:'构建 Agent',status:'completed',attempt:1}];body.error={category:'validation',reason:'正常版本未通过，尚不能发布'};await route.fulfill({response:res,json:body})});
 await page.goto('/generate/'+created.id);
 await expect(page.getByRole('alert')).toContainText('正常版本未通过');
 await page.getByText('阶段执行记录（3）',{exact:true}).click();
 await expect(page.getByText('独立评测 Agent · 修复补丁被拒绝 · 调用 #1',{exact:true})).toBeVisible();
 await expect(page.getByText('契约 Agent · 供应商响应格式不兼容 · 调用 #2',{exact:true})).toBeVisible();
 await expect(page.getByText('构建 Agent · 资产校验通过（非最终验收） · 调用 #1',{exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'审核通过并发布'})).toHaveCount(0);
 const denied=await request.post('/api/author/generation/'+created.id+'/publish',{data:{approved:true,note:'无执行证据不能发布，这个请求必须被拒绝',review_digest:'0'.repeat(64)}});
 expect(denied.status()).toBe(400);
});

test('自动诊断修复、预算耗尽和明确授权新批次（MOCK，实际Docker）',async({page,request},info)=>{
 test.setTimeout(180000);
 const health=await (await request.get('/api/health')).json();
 test.skip(!health.docker_available,'Docker unavailable; no host fallback');
 expect(health.agent_mode).toBe('mock');
 const {execFileSync}=await import('node:child_process');
 const path=await import('node:path');
 const root=path.resolve(process.cwd(),'..');
 const parent=execFileSync(path.join(root,'.venv/bin/python'),['-m','scripts.seed_roles_browser_fixture'],{cwd:root,env:{...process.env,AGENT_MODE:'mock',AGENTLAB_DATA:'/tmp/agentlab-playwright'},encoding:'utf8'}).trim();
 await page.goto('/generate/'+parent);
 await expect(page.locator('strong[role=status]')).toHaveText('本批预算耗尽');
 async function newBatch(count:number){
  await page.getByRole('button',{name:'重新生成（消耗Token）',exact:true}).click();
  await page.getByLabel('新批次最大模型请求').fill(String(count));
  await expect(page.getByRole('button',{name:'确认新预算并重新生成'})).toBeDisabled();
  await page.getByLabel('我明确批准上述新批次预算；旧记录保持不变').check();
  await page.getByRole('button',{name:'确认新预算并重新生成'}).click();
 }
 await newBatch(1);
 await expect(page).not.toHaveURL('/generate/'+parent);
 await expect(page.locator('strong[role=status]')).toHaveText('本批预算耗尽',{timeout:15000});
 const spent=page.url().split('/').pop();
 const one=await (await request.get('/api/generation/jobs/'+spent)).json();
 expect(one.budget.requests).toBe(1);expect(one.parent_job).toBe(parent);
 await page.reload();await expect(page.locator('strong[role=status]')).toHaveText('本批预算耗尽');
 await newBatch(8);
 await expect(page.locator('strong[role=status]')).toHaveText('等待作者审核',{timeout:100000});
 const finalId=page.url().split('/').pop();
 const done=await (await request.get('/api/generation/jobs/'+finalId)).json();
 expect(done.matrix.passed).toBe(true);
 expect(done.attempts.map((a:any)=>a.stage)).toEqual(['diagnosis','repair_build','teaching']);
 expect(done.parent_job).toBe(spent);
 await page.reload();await expect(page.locator('strong[role=status]')).toHaveText('等待作者审核');
 expect((await (await request.get('/api/generation/jobs/'+spent)).json()).budget.requests).toBe(1);
 expect((await (await request.get('/api/generation/jobs/'+parent)).json()).matrix.passed).toBe(false);
 await info.attach('roles-batch-evidence',{body:JSON.stringify({parent,spent,done},null,2),contentType:'application/json'});
});

test('需求澄清、局部契约版本、重新验证和刷新（MOCK，实际Docker）',async({page,request},info)=>{
 test.setTimeout(150000);
 const health=await (await request.get('/api/health')).json();
 test.skip(!health.docker_available,'Docker unavailable; no host fallback');expect(health.agent_mode).toBe('mock');
 const {execFileSync}=await import('node:child_process');const path=await import('node:path');
 const root=path.resolve(process.cwd(),'..');
 const id=execFileSync(path.join(root,'.venv/bin/python'),['-m','scripts.seed_contract_browser_fixture'],{cwd:root,env:{...process.env,AGENT_MODE:'mock',AGENTLAB_DATA:'/tmp/agentlab-playwright'},encoding:'utf8'}).trim();
 const before=await (await request.get('/api/generation/jobs/'+id)).json();
 await page.goto('/generate/'+id);
 await page.getByRole('button',{name:'重新生成（消耗Token）',exact:true}).click();
 await page.getByRole('button',{name:'恢复当前批次',exact:true}).click();
 await expect(page.getByRole('heading',{name:'需要你明确需求'})).toBeVisible({timeout:15000});
 await expect(page.getByRole('button',{name:'提交需求澄清并继续（消耗Token）'})).toBeDisabled();
 const answer='返回所有整数的算术和，空列表返回0。';
 await page.getByLabel('需求回答 intent').fill(answer);
 await page.reload();await expect(page.getByLabel('需求回答 intent')).toHaveValue(answer);
 await page.getByRole('button',{name:'提交需求澄清并继续（消耗Token）'}).click();
 await expect(page.locator('strong[role=status]')).toHaveText('等待作者审核',{timeout:100000});
 await expect(page.getByRole('heading',{name:'公开契约 · 版本 2'})).toBeVisible();
 await expect(page.getByLabel('契约 scenario')).toHaveValue(before.contract.scenario+'需求说明：'+answer);
 const after=await (await request.get('/api/generation/jobs/'+id)).json();
 expect(after.contract_version).toBe(2);expect(after.matrix.passed).toBe(true);
 expect(after.matrix.contract_hash).toBe(after.contract_hash);
 expect(after.contract.behaviors).toEqual(before.contract.behaviors);
 expect(after.contract.input_schema).toEqual(before.contract.input_schema);
 expect(after.contract.files).toEqual(before.contract.files);
 expect(after.contract_reviews.at(-1).proposal.changes.map((c:any)=>c.path)).toEqual(['/scenario']);
 expect(after.attempts.filter((a:any)=>a.stage==='contract_check')).toHaveLength(2);
 await page.reload();await expect(page.getByRole('heading',{name:'公开契约 · 版本 2'})).toBeVisible();
 await expect(page.getByRole('heading',{name:'契约局部修订记录'})).toBeVisible();
 await info.attach('local-contract-evidence',{body:JSON.stringify({before,after},null,2),contentType:'application/json'});
});

test('回退后成本展示与作者摘要（MOCK，实际Docker）',async({page,request})=>{
 test.setTimeout(90000);
 const health=await (await request.get('/api/health')).json();test.skip(!health.docker_available,'Docker 不可用，禁止宿主降级');
 const {execFileSync}=await import('node:child_process');
 const path=await import('node:path');const root=path.resolve(process.cwd(),'..');
 const id=execFileSync(path.join(root,'.venv/bin/python'),['-m','scripts.seed_reliability_browser_fixture'],{cwd:root,env:{...process.env,AGENT_MODE:'mock',AGENTLAB_DATA:'/tmp/agentlab-playwright'},encoding:'utf8'}).trim();
 await page.goto('/generate/'+id);
 await expect(page.getByRole('status')).toContainText('失败');
 await expect(page.getByLabel('修复进展与实际用量')).toContainText('不再按无进展提前终止');
 await expect(page.getByLabel('修复进展与实际用量')).toContainText('未返回');
 await page.getByRole('button',{name:'打开私有资产审核'}).click();
 const summary=page.getByLabel('作者审核摘要');
 await expect(summary).toContainText('未通过门禁');
 await expect(summary).toContainText(id);
 await expect(summary.getByText('参考修复代码与思路审核').locator('..')).not.toHaveAttribute('open','');
 await expect(page.getByRole('button',{name:'审核通过并发布'})).toBeDisabled();
 await page.getByRole('button',{name:'重新生成（消耗Token）',exact:true}).click();
 await expect(page.getByRole('button',{name:'确认新预算并重新生成'})).toBeDisabled();
 await page.reload();await expect(page.getByRole('status')).toContainText('失败');
 const author=await (await request.get('/api/author/generation/'+id)).json();
 const publicJob=await (await request.get('/api/generation/jobs/'+id)).json();
 expect(author.summary.variant_results.length).toBeGreaterThan(0);
 expect(publicJob.matrix.gates.evasion_witnesses).toBeUndefined();
 expect(publicJob.matrix.evasion_witnesses).toBeUndefined();
 expect((await request.post('/api/author/generation/'+id+'/publish',{data:{approved:true,note:'失败矩阵不得发布的自动化测试',review_digest:'invalid'}})).ok()).toBe(false);
});
